"""Validation contracts for curated market data."""

from gold_forecasting.validation.candles import (
    CANDLE_KEY_COLUMNS,
    REQUIRED_CANDLE_COLUMNS,
    SUPPORTED_TIMEFRAMES,
    CandleGap,
    CandleValidationError,
    CandleValidationResult,
    GapReport,
    detect_gaps,
    validate_candles,
)
from gold_forecasting.validation.quality import (
    DailyDataQualityRecord,
    DataQualityError,
    DataQualityReport,
    ExpectationBasis,
    ExplicitMarketCalendarPolicy,
    GapClassification,
    GapQualityRecord,
    KnownGap,
    MarketCalendarPolicy,
    MarketState,
    MarketStatus,
    ObservedSourceCalendarPolicy,
    QualityStatus,
    UtcMarketWindow,
    WeeklyOpenWindow,
    build_daily_data_quality,
)

__all__ = [
    "CANDLE_KEY_COLUMNS",
    "REQUIRED_CANDLE_COLUMNS",
    "SUPPORTED_TIMEFRAMES",
    "CandleGap",
    "CandleValidationError",
    "CandleValidationResult",
    "DailyDataQualityRecord",
    "DataQualityError",
    "DataQualityReport",
    "ExpectationBasis",
    "ExplicitMarketCalendarPolicy",
    "GapClassification",
    "GapQualityRecord",
    "GapReport",
    "KnownGap",
    "MarketCalendarPolicy",
    "MarketState",
    "MarketStatus",
    "ObservedSourceCalendarPolicy",
    "QualityStatus",
    "UtcMarketWindow",
    "WeeklyOpenWindow",
    "build_daily_data_quality",
    "detect_gaps",
    "validate_candles",
]
