"""Replaceable market-data ingestion adapters."""

from gold_forecasting.ingestion.contracts import (
    M1IngestionBatch,
    M1Provider,
    ProviderConfigurationError,
    ProviderFactory,
    RawArtifact,
    create_m1_provider,
    register_m1_provider,
    registered_m1_adapters,
)
from gold_forecasting.ingestion.histdata import (
    HISTDATA_BASE_URL,
    HISTDATA_INSTRUMENT,
    HISTDATA_SOURCE,
    HISTDATA_SOURCE_SYMBOL,
    HISTDATA_TIMEFRAME,
    HISTDATA_USER_AGENT,
    HistDataArchive,
    HistDataArchiveError,
    HistDataDownloadError,
    HistDataError,
    HistDataIngestionResult,
    HistDataM1Provider,
    HistDataParseError,
    download_histdata_year,
    parse_histdata_m1,
)

__all__ = [
    "HISTDATA_BASE_URL",
    "HISTDATA_INSTRUMENT",
    "HISTDATA_SOURCE",
    "HISTDATA_SOURCE_SYMBOL",
    "HISTDATA_TIMEFRAME",
    "HISTDATA_USER_AGENT",
    "HistDataArchive",
    "HistDataArchiveError",
    "HistDataDownloadError",
    "HistDataError",
    "HistDataIngestionResult",
    "HistDataM1Provider",
    "HistDataParseError",
    "M1IngestionBatch",
    "M1Provider",
    "ProviderConfigurationError",
    "ProviderFactory",
    "RawArtifact",
    "create_m1_provider",
    "download_histdata_year",
    "parse_histdata_m1",
    "register_m1_provider",
    "registered_m1_adapters",
]
