"""Replaceable market-data ingestion adapters."""

from gold_forecasting.ingestion.contracts import (
    IncrementalM1Provider,
    M1IngestionBatch,
    M1Provider,
    M1Resource,
    M1ResourcePage,
    PaginationMode,
    ProviderCapabilities,
    ProviderConfigurationError,
    ProviderFactory,
    RawArtifact,
    ResumeMode,
    RevisionMode,
    create_m1_provider,
    register_m1_provider,
    registered_m1_adapters,
)
from gold_forecasting.ingestion.histdata import (
    HISTDATA_BASE_URL,
    HISTDATA_CAPABILITIES,
    HISTDATA_INSTRUMENT,
    HISTDATA_SOURCE,
    HISTDATA_SOURCE_SYMBOL,
    HISTDATA_TIMEFRAME,
    HISTDATA_USER_AGENT,
    HistDataArchive,
    HistDataArchiveError,
    HistDataDownloadError,
    HistDataError,
    HistDataIngestionResult,
    HistDataM1Provider,
    HistDataParseError,
    download_histdata_year,
    parse_histdata_m1,
)
from gold_forecasting.ingestion.transport import BoundedHttpRequester, HttpRequestPolicy
from gold_forecasting.ingestion.updater import (
    IncrementalUpdateError,
    IncrementalUpdateResult,
    update_m1_history,
)

__all__ = [
    "HISTDATA_BASE_URL",
    "HISTDATA_CAPABILITIES",
    "HISTDATA_INSTRUMENT",
    "HISTDATA_SOURCE",
    "HISTDATA_SOURCE_SYMBOL",
    "HISTDATA_TIMEFRAME",
    "HISTDATA_USER_AGENT",
    "BoundedHttpRequester",
    "HistDataArchive",
    "HistDataArchiveError",
    "HistDataDownloadError",
    "HistDataError",
    "HistDataIngestionResult",
    "HistDataM1Provider",
    "HistDataParseError",
    "HttpRequestPolicy",
    "IncrementalM1Provider",
    "IncrementalUpdateError",
    "IncrementalUpdateResult",
    "M1IngestionBatch",
    "M1Provider",
    "M1Resource",
    "M1ResourcePage",
    "PaginationMode",
    "ProviderCapabilities",
    "ProviderConfigurationError",
    "ProviderFactory",
    "RawArtifact",
    "ResumeMode",
    "RevisionMode",
    "create_m1_provider",
    "download_histdata_year",
    "parse_histdata_m1",
    "register_m1_provider",
    "registered_m1_adapters",
    "update_m1_history",
]
